#!/usr/bin/env bash
#
# zrecast — every number the documentation publishes, regenerated and compared.
#
# Two rules, and between them no count in a document can go stale unnoticed:
#
#   1. A block between `<!-- BEGIN GENERATED <command> -->` and
#      `<!-- END GENERATED -->` must equal that command's output. The marker
#      names the generator, so a reader can rerun it.
#   2. Outside those blocks a document may not state a multi-digit number at
#      all, unless tools/doc_numbers.txt allows it with a reason. A number
#      that belongs to the tree belongs in a generated block.
#
# Usage:
#   ci/check-docs.sh           # compare, fail on any difference
#   ci/check-docs.sh --write   # rewrite the blocks from their generators
#
# ZIG is passed through to the generators; ci/measurements.sh has to build.

set -uo pipefail
cd "$(dirname "$0")/.."

exec python3 - "${1:-}" <<'PY'
import difflib, pathlib, re, subprocess, sys

write = sys.argv[1] == "--write"
docs = sorted(pathlib.Path(".").glob("*.md"))
block = re.compile(
    r"(?P<open><!-- BEGIN GENERATED (?P<cmd>[^>]+?) -->\n)"
    r"(?P<body>.*?)"
    r"(?P<close><!-- END GENERATED -->)",
    re.S,
)
failures = 0

for doc in docs:
    text = doc.read_text(encoding="utf-8")
    out = []
    end = 0
    for m in block.finditer(text):
        cmd = m.group("cmd").strip()
        run = subprocess.run(["bash", "-c", cmd], capture_output=True, text=True)
        if run.returncode != 0:
            print("%s: generator failed: %s\n%s" % (doc, cmd, run.stderr.strip()))
            failures += 1
            continue
        want = run.stdout.replace("\r\n", "\n")
        if not want.endswith("\n"):
            want += "\n"
        have = m.group("body")
        if have != want:
            failures += 1
            print("%s: the block generated by `%s` is stale:" % (doc, cmd))
            for line in difflib.unified_diff(
                have.splitlines(True), want.splitlines(True),
                fromfile="in the document", tofile=cmd, n=1,
            ):
                print("  " + line.rstrip("\n"))
        out.append(text[end:m.start()])
        out.append(m.group("open") + want + m.group("close"))
        end = m.end()
    if write and out:
        out.append(text[end:])
        # open() rather than Path.write_text: the newline keyword reached
        # it only in Python 3.13, and hosted runners are older.
        with open(doc, "w", encoding="utf-8", newline="\n") as f:
            f.write("".join(out))

if write:
    sys.exit(1 if failures else 0)

# Rule 2. Numbers inside a generated block, a fenced code block, a link target
# or an identifier (x86_64, 0.16.0) are not hand-written claims.
allowed = {}
for line in pathlib.Path("tools/doc_numbers.txt").read_text(encoding="utf-8").splitlines():
    if not line.strip() or line.startswith("#"):
        continue
    number, _, reason = line.partition("\t")
    allowed.setdefault(number.strip(), reason.strip())

used = set()
number = re.compile(r"(?<![0-9A-Za-z_.\-/])[0-9][0-9 ,]*[0-9](?![0-9A-Za-z_.\-/])")
def blank(m):
    """Erase a region, keeping its newlines so line numbers stay true."""
    return "\n" * m.group(0).count("\n")


for doc in docs:
    text = block.sub(blank, doc.read_text(encoding="utf-8"))
    text = re.sub(r"```.*?```", blank, text, flags=re.S)
    text = re.sub(r"`[^`\n]*`", blank, text)
    text = re.sub(r"\]\([^)]*\)", blank, text)
    for n, line in enumerate(text.splitlines(), 1):
        for found in number.finditer(line):
            token = found.group(0)
            if token in allowed:
                used.add(token)
                continue
            failures += 1
            print("%s:%d: the number %s is written by hand" % (doc, n, token))
            print("       put it in a generated block, or give tools/"
                  "doc_numbers.txt a line saying why it cannot go stale")

# An entry that allows nothing is a rule about a document that no longer says
# what it describes -- the same staleness the list exists to prevent.
for token in sorted(set(allowed) - used):
    failures += 1
    print("tools/doc_numbers.txt: %s is allowed but no document states it" % token)

if failures == 0:
    print("OK documented numbers are generated or accounted for")
sys.exit(1 if failures else 0)
PY
